### ISSUE TITLE
scanimage instead of scanadf

### ISSUE THREAD

**Issue by budda85** [rocketraman/sane-scan-pdf#50]
is it possible to use the script with scanimage instead of scanadf?
I'm using Manjaro and there is no scanadf.

**Comment by rocketraman** [comment]
Not at the moment -- the script relies on the `-S` parameter of `scanadf` to process each page scanned.

What are you trying to do exactly? If you are only scanning a single page then a lot of what the script does is not relevant.

On Fedora, `scanadf` is provided by the `sane-frontends` package whereas `scanimage`  is provided by `sane-backends`. Perhaps you just need to install the equivalent Manjaro package?

**Comment by budda85** [comment]
I have a Fujitsu ix500 and would like to control it via the scan button. The scanner should then scan in duplex mode, remove the white pages and save the file as pdf.
I can query the button press with scanadf and then I just want to use your script to do the rest. But as I found out, scanadf is not available for manjaro/arch and is probably no longer actively maintained.

**Comment by rocketraman** [comment]
> But as I found out, scanadf is not available for manjaro/arch and is probably no longer actively maintained.

I don't believe that is right: the last change made to `scanadf.c` was 4 weeks ago: https://gitlab.com/sane-project/frontends/-/tree/master/src.

I don't know how this script would work without the ability of `scanadf` to scan multiple pages at a time. If you have any suggestions or want to submit a PR, please feel free but otherwise I'll go ahead and close this.

**Comment by rocketraman** [comment]
BTW, looks like you can still load sane-frontends from AUR: https://aur.archlinux.org/packages/sane-frontends.
